apiVersion: v1
kind: Service
metadata:
  name: temadeintegratinggithubwithazurepipelines
spec:
  type: LoadBalancer
  selector:
    app: temadeintegratinggithubwithazurepipelines
  ports:
    - port: 80        # Public port exposed externally
      targetPort: 3000 # Internal app port
